{
 "title": "Kafka Orders Overview",
 "refresh": "10s",
 "panels": [
  {
   "title": "Consumer Lag (order-service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"order-service\"})"
    }
   ]
  },
  {
   "title": "BUY Success (5m)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(order_processed_total{type=\"BUY\",result=\"success\"}[5m])"
    }
   ]
  },
  {
   "title": "SELL Success (5m)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "increase(order_processed_total{type=\"SELL\",result=\"success\"}[5m])"
    }
   ]
  },
  {
   "title": "Failed Orders (5m)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "increase(order_processed_total{result=\"failed\"}[5m])"
    }
   ]
  }
 ]
}